curl --location --request PUT '<insert presignedUrl generated by https://api.pdf.co/v1/file/upload/get-presigned-url >' \
--header 'x-api-key: {{x-api-key}}' \
--form 'file=@/Users/em/Downloads/logo.png'