import requests

url = "<insert presignedUrl generated by https://api.pdf.co/v1/file/upload/get-presigned-url >"

payload = {}
files = [
		('file', open('/Users/em/Downloads/logo.png','rb'))
]
headers = {
		'x-api-key': '{{x-api-key}}'
}

response = requests.request("PUT", url, headers=headers, data = payload, files = files)

print(response.text.encode('utf8'))
